### PR TITLE
Blockchain data context

### PR DESCRIPTION
**Pull request by adamgall**
Create a new top-level context for holding blockchain-specific data, such as current block number and current (blockchain) timestamp.

Originally these were in the `daoData` context, but they're not specific to DAOs so they've been moved.

As always, read through the commits in order to see the logical progression of changes.

### CODE REVIEW

**Review by Da-Colon — COMMENTED** [review]
@adamgall (minor) do you think maybe these files `blockchainData` and `daoData` and moved to a `/data` or `/context` directory?

**Comment by adamgall** [comment]
> @adamgall (minor) do you think maybe these files `blockchainData` and `daoData` and moved to a `src/data` or `src/context` directory?

Are you suggesting moving the entire `blockchainData` and `daoData` directories? (probably also include `web3` directory)? I like the idea of moving them all into a top level `src/contexts` directory, yes.

**Comment by adamgall** [comment]
@Da-Colon what do you think of this?

**Review by Da-Colon — APPROVED** [review]
yessir. SHIP IT!

**Pull request merged**
