### PR TITLE
Create Dao Form Updates

### PR DESCRIPTION
**Pull request by Da-Colon**
## Overview
Updates Pages/Components on `/Dao/new route`

## Note
- Per Conversation with @dannydecent . Some designs updates have been made to tokenAllocations

## Changes
- Updates Inputs to new Form Input
- Updates Buttons to new Form buttons
- Fixed Some areas where inputs where 'uncontrolled'
- updated Input Component with Helper class
- prevent New Fractal name changing when update DAO name (uses Dao name past first stop)
- adds seperator between inputs and helperText
- updates buttons in tokenAllocation to new TextButtons
- updates Token Allocation Responsiveness

## Screenshots

image

image

image

## Mobile
image

image

### CODE REVIEW

**Comment by dannydecent** [comment]
image


Token Allocation should be on its own screen. Update the colors off Add Allocation and update "X" to "Remove" (see screenshot below)

image

**Comment by Da-Colon** [comment]
@dannydecent asked and received sir. Screenshots have been updated

**Comment by adamgall** [comment]
Are the font weights on `Add Allocation` and `Remove` correct?

**Comment by Da-Colon** [comment]
> Are the font weights on Add Allocation and Remove correct?

Good catch. This has been fixed

**Review by adamgall — APPROVED** [review]

**Pull request merged**
